[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
gifs_dapp_containerized = "D5ErZkzVpvkhv4pZoFWoN9Fku7SWzwpKxqux9rMwqNR7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
