[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
gifs_dapp_containerized = "DscCutv9QLURJGrs1hwoYAgeztnVyZQnkau5ZLnfLKQ9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
